### ISSUE TITLE
Better option syntax

### ISSUE THREAD

**Issue by flaviut** [flaviut/nre#11]
Selecting options is a nasty process right now, `re"foo"` -> `re(r"foo", "ix")`. It is possible to use the PCRE option syntax,  `re"(?ix)foo"`, but that has the disadvantage of only supporting four options.

A possible solution would be to parse the `(?...)` blocks in nre and convert them to options. This would only be done for option blocks at the beginning of the string, and there would have to be some logic to avoid parsing block like `(?P=foo)` as option blocks.

Are there other suggestions?

**Comment by oprypin** [comment]
I support the idea to parse flags from the beginning of the string.

http://pcre.org/pcre.txt - search for "MATCH POINT RESET" and look below to see all the craziness.

Relevant/interesting excepts:

```
(?i)(?s)(?x)(?X)(?m)(?U)
(?J)(?-J)
(?|
(?:
(?C1)
(?!a)
(?>
(?=  (?!  (?<=  (?<!
(?<name>...) (?'name'...) (?P<name>...)
(?(condition)yes-pattern|no-pattern)
(?#
(?p{...})
(?R)
(?1) (?-2) (?+2)
(?&name)
(?{})  (??{})
```

> `(?im-sx)`, which sets  PCRE_CASELESS  and PCRE_MULTILINE while unsetting PCRE_DOTALL and PCRE_EXTENDED
> 
> An  option  change  within a subpattern (see below for a description of subpatterns) affects only that part of the subpattern that follows  it, so `(a(?i)b)c` matches _abc_ and _aBc_ and no other strings (assuming PCRE_CASELESS is not used).
> 
> As a convenient shorthand, if any option settings are required  at  the start  of  a  non-capturing  subpattern,  the option letters may appear between the "?" and the ":". Thus the two patterns
> 
> ```
> (?i:saturday|sunday)
> (?:(?i)saturday|sunday)
> ```
> 
> match exactly the same set of strings.

**Comment by dom96** [comment]
In what way is that nasty?

**Comment by oprypin** [comment]
`(?flags)` can occur at any point in the string, it's best to leave them to PCRE. There are, however, also `(*FLAGS)`. PCRE says this about them:

> These are recognized only at the very start of  the  pattern  or  after
> option settings with a similar syntax.

We can simply define some more of these and say that they must go first in the string. First let's see what can already be handled inside the regular expressions and what can't.
- [X] `8`, `u`, `<utf8>` = _UTF8_  
  `(*UTF8)`
- [ ] `9`, `<no_utf8>` = _NEVER_UTF_  
- [ ] `A`, `<anchored>` = _ANCHORED_  
- [ ] `E`, `<dollar_endonly>` = _DOLLAR_ENDONLY_  
- [ ] `f`, `<firstline>` = _FIRSTLINE_  
- [X] `i`, `<case_insensitive>` = _CASELESS_  
  `(?i)`
- [X] `m`, `<multiline>` = _MULTILINE_  
  `(?m)`
- [ ] `N`, `<no_auto_capture>` = _NO_AUTO_CAPTURE_  
- [X] `s`, `<dotall>` = _DOTALL_  
  `(?s)`
- [X] `U`, `<ungreedy>` = _UNGREEDY_  
  `(?U)`
- [X] `W`, `<ucp>` = _UCP_  
  `(*UCP)`
- [X] `X`, `<extra>` = _EXTRA_  
  `(?X)`
- [X] `x`, `<extended>` = _EXTENDED_  
  `(?x)`
- [X] `Y`, `<no_start_optimize>` = _NO_START_OPTIMIZE_  
  `(*NO_START_OPT)`
- [X] `<cr>` = _NEWLINE_CR_  
  `(*CR)`
- [X] `<lf>` = _NEWLINE_LF_  
  `(*LF)`
- [X] `<crlf>` = _NEWLINE_CRLF_  
  `(*CRLF)`
- [X] `<anycrlf>` = _NEWLINE_ANYCRLF_  
  `(*ANYCRLF)`
- [X] `<any>` = _NEWLINE_ANY_  
  `(*ANY)`
- [X] `<bsr_anycrlf>` = _BSR_ANYCRLF_  
  `(*BSR_ANYCRLF)`
- [X] `<bsr_unicode>` = _BSR_UNICODE_  
  `(*BSR_UNICODE)`
- [ ] `<js>` = _JAVASCRIPT_COMPAT_  
- [ ] `<no_study>`

**Comment by oprypin** [comment]
I have implemented this. https://github.com/BlaXpirit/nre/commits/inline-options

`(*NEVER_UTF|ANCHORED|DOLLAR_ENDONLY|FIRSTLINE|NO_AUTO_CAPTURE|JAVASCRIPT_COMPAT)` are filtered out of the pattern string (see [**tests**](https://github.com/BlaXpirit/nre/blob/inline-options/test/init.nim#L9))

**Comment by oprypin** [comment]
Let's provide some examples, based on these:
- `re(r"abc", "i")`
- `re(r"abc", "ix<anycrlf>")`

What I [implemented](https://github.com/BlaXpirit/nre/commits/inline-options) above (actually, this currently works as well, but some flags are missing and inconsistent):
- `re"(?i)abc"`
- `re"(*ANYCRLF)(?ix)abc"`

I have also [implemented](https://github.com/BlaXpirit/nre/commits/short-options)
- `re"abc"/i`
- `re"(*ANYCRLF)abc"/ix`

Some new ideas after discussion with _flaviut_:
- `re"abc".opts"i"`
- `re"abc".opts"ix<anycrlf>"`


- `re"abc"{i}`
- `re"abc"{i, x, anycrlf}`

I was unable to implement this last one because of https://github.com/Araq/Nim/issues/2545

Another problem is one can't store the flags in a variable to apply to multiple regexes.
To counteract this, a possibility is to use actual enums for these flags, without any single-letter variants, but also implement this shorthand syntax.

**Comment by flaviut** [comment]
I've implemented `re"abc".opts"i"` and `re"abc".opts"ix<anycrlf>"` in the mentioned commit, but I'm tempted to just leave things the way they are. While it may be a bit of a hassle type things out, avoiding DSLs is a fine goal.

I realize I've been going in circles on this, and I apologize.
