### ISSUE TITLE
Idea for documentation: re"\+" vs re("\+")

### ISSUE THREAD

**Issue by bluenote10** [flaviut/nre#16]
I just got confused by the fact that `re"\+"` works while `re("\+")` fails. The error `invalid character constant` also suggested that there is an issue in nre, and I had to do a bit of research to see what is going on here.

Maybe it is a good idea to include a reminder of "generalized raw string literals" in the documentation to prevent others from falling into this trap. Maybe something like this:

Note: There is a difference between for instance `re"\+"` and `re("\+")` as a result of Nim's generalized raw string literals. If there is no space between `re` and the following string literal, the literal is interpreted as a raw literal and passed to the `re` function. On the other hand, for expressions like `re "\+"`, `re("\+")`, and `let s = "\+"; re(s)` Nim will try to parse the string for escape sequences. This results in an error `invalid character constant`, because `\+` is not a valid escape character. In this case, `"\+"` has to be written either by proper escaping `re("\\+")` or by a raw string literal `re(r"\+")`.

**Comment by flaviut** [comment]
This is more-or-less covered:

> Represents the pattern that things are matched against, constructed with re(string). Examples: `re"foo"`, `re(r"(*ANYCRLF)(?x)foo # comment"`.
