### ISSUE TITLE
Sample code does not compile.

### ISSUE THREAD

**Issue by axbender** [flaviut/nre#19]
Sorry, I keep getting: x.nim(4, 25) Error: undeclared identifier: 'get':

``` nim
#mport optional_t.nonstrict
import nre

if "abc".match(re"(\w)").get.captures[0]                 == "a":     echo "[1]"
if "abc".match(re"(?<letter>\w)").get.captures["letter"] == "a":     echo "[2]"
if "abc".match(re"(\w)\w").get.captures[-1]              == "ab":    echo "[3]"
if "abc".match(re"(\w)").get.captureBounds[0]            == 0 .. 0:  echo "[4]"
if "abc".match(re"").get.captureBounds[-1]               == 0 .. -1: echo "[5]"
if "abc".match(re"abc").get.captureBounds[-1]            == 0 .. 2:  echo "[6]"
```

**Comment by flaviut** [comment]
That's because the latest version of nre depends on Nim devel and the `options` package on its stdlib. You'll have to import that to get access to the get procedure.

**Comment by axbender** [comment]
Thanks for the answer. Questions:
1) How would I do that?
2) How would I "emulate" re.match()'s behavior with nre.match() when supplying the "matches" parameter with re.match()?

**Comment by flaviut** [comment]
>  1) How would I do that?

Instructions on cloning and compiling the devel branch can be found [here](https://github.com/Araq/Nim#compiling). To import, just do  `import options`.

>  2) How would I "emulate" re.match()'s behavior with nre.match() when supplying the "matches" parameter with re.match()?

I'm not sure I understand what you want to do, but `let matches = "abc".match(re"(\w)").get.matches.toSeq`.

**Comment by axbender** [comment]
Thanks for the answers.

I was, however, somewhat unspecific: I am on the devel branch, and the missing info was `import options` (maybe you could update your docs? and yes, I [c|sh]ould have concluded this myself...).

But (there's always a "but" isn't it?), adding the `import` statement I get errors for lines 7ff:

> x.nim(7, 58) Error: type mismatch: got (Option[Slice[system.int]], Slice[system.int])
> but expected one of:
> system.==(x: ref T, y: ref T)

Can that be expected?

As for the second part of your answer: Your example compiles fine once I change `...get.matches.toSeq` for `...get.captures.toSeq`.

**Comment by flaviut** [comment]
On Jun 3, 2015 2:48 AM, "axbender" notifications@github.com wrote:

> Thanks for the answers.
> 
> I was, however, somewhat unspecific: I am on the devel branch, and the missing info was import options (maybe you could update your docs? and yes, I [c|sh]ould have concluded this myself...).
> 
> But (there's always a "but" isn't it?), adding the import statement I get errors for lines 7ff:
> 
> > x.nim(7, 58) Error: type mismatch: got (Option[Slice[system.int]], Slice[system.int])
> > but expected one of:
> > system.==(x: ref T, y: ref T)
> 
> Can that be expected?

Yes, the error tells you exactly where the problem is: you can't compare an option and a slice for equality. Try unboxing the option, that might do what you want.

> As for the second part of your answer: Your example compiles fine once I change ...get.matches.toSeq for ...get.captures.toSeq.

Sorry about that, I typed the wrong thing.
