### ISSUE TITLE
Remove substring cache

### ISSUE THREAD

**Issue by flaviut** [flaviut/nre#2]
There is an "optimization" done where the substrings for a given match are cached, but it needs to be investigated whether this is worth the [de]allocation overhead of an `ref RegexMatch` and of a `seq`.
- Is it common for a substring to be used `> 3` times?
- Is it reasonable to expect the user to do his own caching in those circumstances?

Switching to an immutable `RegexMatch` also has the advantage of better serialization, although I haven't given thought to how serialization should work yet.

**Comment by oprypin** [comment]
I don't find such a cache useful. An overhead for using a substring multiple times should be expected. A mention in the docs can help.

**Comment by flaviut** [comment]
Done in a1110ebb14e7ca1bd99ceb05da986ba902662bbc: Also converted RegexMatch from ref to Option as it no longer needs to be mutated.
