### ISSUE TITLE
Result of nonmatching split operations

### ISSUE THREAD

**Issue by axbender** [flaviut/nre#20]
In JS/Perl I get:

``` javascript
WScript.Echo("9".split(/\son\s/));   // 9
```

``` perl
print split(/\son\s/, "9");   # 9
```

While in nim with nre I get:

``` nim
import nre
echo "9".split(re"\son\s")   # @[]
```

These are not identical but should be - given your statement on split() `This works according to the rules that Perl and Javascript use...`.

**Comment by BlaXpirit** [comment]
Looks like a bad bug.
