### ISSUE TITLE
\d+ not working

### ISSUE THREAD

**Issue by RokkuCode** [flaviut/nre#21]
I am parsing dig output: `dig +noall +stat @<mydns> <domain>`. Result of dig command:

```
;; Query time: 37 msec
;; SERVER: 1.2.3.4#53(1.2.3.4)
;; WHEN: Wed Jul 29 02:09:29 CEST 2015
;; MSG SIZE  rcvd: 45
```

code that works:

```
let digrex = re("Query time: (?<digout>([0-9]+))")
var digout: string = strip(output.find(digrex).get.captures["digout"])
echo digout
```

as an alternative this works too:

```
let digrex = re("Query time: (?<digout>([[:digit:]]+))")
var digout: string = strip(output.find(digrex).get.captures["digout"])
echo digout
```

code that does not work

```
let digrex = re("Query time: (?<digout>(\d+))")
var digout: string = strip(output.find(digrex).get.captures["digout"])

Error: invalid character constant
```

Why does this not work, until pcre has `\d`for digits as far as I know.

Thanks

PS:
nre  [1.0.0]
Nim Compiler Version 0.11.2

**Comment by flaviut** [comment]
Nim is interpreting the escape sequence itself, the raw characters are not
being passed to nre.

Try `re(r"\d")` or `re"\d"`, neither of which will interpret escape
sequences.

For further reference, see the [Raw strings section in the manual.](http://nim-lang.org/docs/manual.html#lexical-analysis-raw-string-literals)
