### ISSUE TITLE
Add re"..."<flags> syntax

### ISSUE THREAD

**Issue by axbender** [flaviut/nre#4]
Using re(r"...", "<flags>") is quite a bit tedious to write.
I wonder if it is possible to implement a re"..."<flags> syntax w/o changing the compiler (=> Araq)?

E.g.
   re(r" *((gca|c2c))", "i")
would then be written as
   re" *((gca|c2c))"i

**Comment by flaviut** [comment]
I don't think that that syntax is possible, but `re"foo".i` should be
possible. I'll investigate as soon as I can get to my computer.

**Comment by oprypin** [comment]
Why does it have to be language syntax?
[Python's library](https://docs.python.org/3/library/re.html), for example, lets you specify flags in the string of the regular expression:
`"(?im)test$"` is case-insensive, multiline `"test$"`.

It may not be the best idea to copy this syntax directly, because PCRE has a lot more flags, and there are bound to be syntax/naming collisions.

Some random suggestions that don't seem to collide with anything: <code>(?/<b>flags</b>)</code> (or `~`)

---

> `re"foo".i` should be possible

I see what you're hinting at, but this probably means defining tons of functions with tiny names and delaying regexp compilation...

**Comment by flaviut** [comment]
That syntax is already supported, from the PCRE man page:

> # OPTION SETTING
> 
> ```
>   (?i)            caseless
>   (?J)            allow duplicate names
>   (?m)            multiline
>   (?s)            single line (dotall)
>   (?U)            default ungreedy (lazy)
>   (?x)            extended (ignore white space)
>   (?-...)         unset option(s)
> ```
> 
> The  following  are  recognized  only at the very start of a pattern or
> after one of the newline or \R options with similar syntax.  More  than
> one of them may appear.
> 
> ```
>   (*LIMIT_MATCH=d) set the match limit to d (decimal number)
>   (*LIMIT_RECURSION=d) set the recursion limit to d (decimal number)
>   (*NO_AUTO_POSSESS) no auto-possessification (PCRE_NO_AUTO_POSSESS)
>   (*NO_START_OPT) no start-match optimization (PCRE_NO_START_OPTIMIZE)
>   (*UTF8)         set UTF-8 mode: 8-bit library (PCRE_UTF8)
>   (*UTF16)        set UTF-16 mode: 16-bit library (PCRE_UTF16)
>   (*UTF32)        set UTF-32 mode: 32-bit library (PCRE_UTF32)
>   (*UTF)          set appropriate UTF mode for the library in use
>   (*UCP)          set PCRE_UCP (use Unicode properties for \d etc)
> ```
> 
> Note  that LIMIT_MATCH and LIMIT_RECURSION can only reduce the value of
> the limits set by the caller of pcre_exec(), not increase them.

---

> > `re"foo".i` should be possible
> 
> I see what you're hinting at, but this probably means defining tons of functions with tiny names and delaying regexp compilation...

Nope, macros and http://nim-lang.org/manual.html#dot-operators should do it without any compile time impact. It would be incredibly hacky though.

**Comment by axbender** [comment]
@flaviut: Thanks for looking into it.

@BlaXpirit: I do not insist on this; it's just a question - though it would be nice to have this "abbreviation". Btw. Perl does have these expressions too (in fact, they invented it ;-) so PCRE should support them. However, I think the proposed solution would be more "Nimish".

**Comment by oprypin** [comment]
PCRE's "option setting" looks more than good enough, unless maybe there are some important flags that aren't supported there.

**Comment by axbender** [comment]
Sorry, flaviut, you answered while I was writing that last post.
So I consider this question as answered. Despite, thanks for looking into it.

**Comment by flaviut** [comment]
Ok, closing it then. I'll be sure to update the documentation to point this out.

**Comment by flaviut** [comment]
@axbender @BlaXpirit See cba3b78, I've made the appropriate changes to the documentation.

**Comment by oprypin** [comment]
Continued in https://github.com/flaviut/nre/issues/11
