### ISSUE TITLE
Create idiomatic variant

### ISSUE THREAD

**Issue by flaviut** [flaviut/nre#6]
@Araq has pointed out that nre uses exclusive upper bounds, when most Nim code uses inclusive upper bounds. There should be a version of nre to use inclusive upper bounds.

**Comment by oprypin** [comment]
One thing that I feel strongly against is the use of Nim's `..` for exclusive upper bounds here.

**Comment by oprypin** [comment]
You should just turn everything to inclusive upper bounds :neutral_face:
